# Generated by Django 4.2.7 on 2025-09-20 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('native_name', models.CharField(max_length=100, verbose_name='nom natif')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='pays par défaut')),
                ('continent', models.CharField(blank=True, max_length=50, verbose_name='continent')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='région')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='emoji du drapeau')),
                ('phone_code', models.CharField(blank=True, max_length=10, verbose_name='indicatif téléphonique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('symbol', models.CharField(max_length=10, verbose_name='symbole')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='devise par défaut')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='taux de change')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='dernière mise à jour')),
                ('decimal_places', models.PositiveIntegerField(default=2, verbose_name='nombre de décimales')),
                ('symbol_position', models.CharField(choices=[('before', 'Avant'), ('after', 'Après')], default='after', max_length=10, verbose_name='position du symbole')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('native_name', models.CharField(max_length=100, verbose_name='nom natif')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='langue par défaut')),
                ('is_rtl', models.BooleanField(default=False, verbose_name='écriture de droite à gauche')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='emoji du drapeau')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordre de tri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Langue',
                'verbose_name_plural': 'Langues',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='taux de taxe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='i18n.country')),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['name'],
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='taux de taxe')),
                ('tax_type', models.CharField(choices=[('vat', 'TVA'), ('sales_tax', 'Taxe de vente'), ('gst', 'GST'), ('other', 'Autre')], default='vat', max_length=20, verbose_name='type de taxe')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='tax_rules', to='products.category', verbose_name='catégories applicables')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='tax_rules', to='products.product', verbose_name='produits applicables')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='i18n.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='i18n.region')),
            ],
            options={
                'verbose_name': 'Règle de taxation',
                'verbose_name_plural': 'Règles de taxation',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='zone par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('countries', models.ManyToManyField(related_name='shipping_zones', to='i18n.country', verbose_name='pays')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('method_type', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('overnight', 'Livraison du jour au lendemain'), ('pickup', 'Retrait en magasin'), ('digital', 'Livraison numérique')], default='standard', max_length=20, verbose_name='type de méthode')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='coût de base')),
                ('cost_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='coût par kg')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='seuil de livraison gratuite')),
                ('min_delivery_days', models.PositiveIntegerField(default=1, verbose_name='délai minimum (jours)')),
                ('max_delivery_days', models.PositiveIntegerField(default=7, verbose_name='délai maximum (jours)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='méthode par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='i18n.shippingzone')),
            ],
            options={
                'verbose_name': 'Méthode de livraison',
                'verbose_name_plural': 'Méthodes de livraison',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='i18n.currency'),
        ),
        migrations.AddField(
            model_name='country',
            name='default_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='i18n.language'),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('product', 'Produit'), ('category', 'Catégorie'), ('brand', 'Marque'), ('page', 'Page'), ('email', 'Email'), ('notification', 'Notification')], max_length=20, verbose_name='type de contenu')),
                ('object_id', models.PositiveIntegerField(verbose_name="ID de l'objet")),
                ('field_name', models.CharField(max_length=100, verbose_name='nom du champ')),
                ('original_text', models.TextField(verbose_name='texte original')),
                ('translated_text', models.TextField(verbose_name='texte traduit')),
                ('is_approved', models.BooleanField(default=False, verbose_name='approuvé')),
                ('is_auto_translated', models.BooleanField(default=False, verbose_name='traduit automatiquement')),
                ('translator', models.CharField(blank=True, max_length=100, verbose_name='traducteur')),
                ('translation_service', models.CharField(blank=True, max_length=100, verbose_name='service de traduction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='i18n.language')),
            ],
            options={
                'verbose_name': 'Traduction',
                'verbose_name_plural': 'Traductions',
                'ordering': ['-updated_at'],
                'unique_together': {('language', 'content_type', 'object_id', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='LocalizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('product', 'Produit'), ('category', 'Catégorie'), ('brand', 'Marque'), ('page', 'Page'), ('email', 'Email'), ('notification', 'Notification')], max_length=20, verbose_name='type de contenu')),
                ('object_id', models.PositiveIntegerField(verbose_name="ID de l'objet")),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('content', models.TextField(blank=True, verbose_name='contenu')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='titre SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='description SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='mots-clés SEO')),
                ('is_published', models.BooleanField(default=True, verbose_name='publié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localized_content', to='i18n.language')),
            ],
            options={
                'verbose_name': 'Contenu localisé',
                'verbose_name_plural': 'Contenus localisés',
                'ordering': ['language', 'content_type'],
                'unique_together': {('language', 'content_type', 'object_id')},
            },
        ),
    ]
