# Generated by Django 4.2.7 on 2025-09-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Silence d'Or", help_text='Nom officiel du site e-commerce', max_length=100, verbose_name='nom du site')),
                ('site_tagline', models.CharField(default='Votre boutique de luxe en ligne', help_text='Slogan ou description courte du site', max_length=200, verbose_name='slogan')),
                ('site_description', models.TextField(default='Découvrez notre sélection exclusive de produits de qualité pour tous vos besoins.', help_text='Description détaillée du site pour le SEO', verbose_name='description du site')),
                ('contact_email', models.EmailField(default='contact@silence-dor.com', help_text='Email principal pour les contacts clients', max_length=254, verbose_name='email de contact')),
                ('contact_phone', models.CharField(default='+33 1 23 45 67 89', help_text='Numéro de téléphone de contact', max_length=20, verbose_name='téléphone')),
                ('contact_address', models.TextField(default='123 Rue de la Paix\n75001 Paris, France', help_text="Adresse physique de l'entreprise", verbose_name='adresse')),
                ('facebook_url', models.URLField(blank=True, help_text='URL de la page Facebook', null=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, help_text='URL du compte Instagram', null=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, help_text='URL du compte Twitter', null=True, verbose_name='Twitter')),
                ('linkedin_url', models.URLField(blank=True, help_text='URL de la page LinkedIn', null=True, verbose_name='LinkedIn')),
                ('company_name', models.CharField(default="Silence d'Or SARL", help_text="Nom légal de l'entreprise", max_length=100, verbose_name="nom de l'entreprise")),
                ('siret_number', models.CharField(blank=True, help_text="Numéro SIRET de l'entreprise", max_length=14, verbose_name='numéro SIRET')),
                ('vat_number', models.CharField(blank=True, help_text='Numéro de TVA intracommunautaire', max_length=20, verbose_name='numéro TVA')),
                ('currency', models.CharField(default='EUR', help_text='Devise principale du site', max_length=3, verbose_name='devise')),
                ('currency_symbol', models.CharField(default='€', help_text='Symbole de la devise', max_length=5, verbose_name='symbole de devise')),
                ('meta_keywords', models.TextField(blank=True, help_text='Mots-clés pour le référencement (séparés par des virgules)', verbose_name='mots-clés SEO')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Identifiant Google Analytics (ex: GA-XXXXXXXXX)', max_length=20, verbose_name='ID Google Analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Informations du site',
                'verbose_name_plural': 'Informations du site',
                'ordering': ['-updated_at'],
            },
        ),
    ]
