# Generated by Django 4.2.7 on 2025-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Image principale de la page d'accueil (recommandé: 800x400px)", null=True, upload_to='site_images/', verbose_name='image hero'),
        ),
    ]
