# Generated by Django 4.2.7 on 2025-09-20 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('method', models.CharField(choices=[('card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20, verbose_name='method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='external id')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='transaction id')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, verbose_name='stripe payment intent id')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, verbose_name='stripe charge id')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='card last four')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='card brand')),
                ('card_exp_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='card exp month')),
                ('card_exp_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='card exp year')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='external id')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=100, verbose_name='stripe refund id')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card', 'Credit Card'), ('bank_account', 'Bank Account'), ('paypal', 'PayPal')], max_length=20, verbose_name='type')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('external_id', models.CharField(max_length=100, verbose_name='external id')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=100, verbose_name='stripe payment method id')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='card last four')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='card brand')),
                ('card_exp_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='card exp month')),
                ('card_exp_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='card exp year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_id'], name='payments_externa_f1691b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_stripe__6cb0ea_idx'),
        ),
    ]
