# Generated by Django 4.2.7 on 2025-09-20 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('content', models.TextField(verbose_name='contenu')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Page hors ligne',
                'verbose_name_plural': 'Pages hors ligne',
            },
        ),
        migrations.CreateModel(
            name='ServiceWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('version', models.CharField(max_length=20, verbose_name='version')),
                ('script_content', models.TextField(verbose_name='contenu du script')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Service Worker',
                'verbose_name_plural': 'Service Workers',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, verbose_name='endpoint')),
                ('p256dh_key', models.CharField(max_length=200, verbose_name='clé P256DH')),
                ('auth_key', models.CharField(max_length=200, verbose_name="clé d'authentification")),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement push',
                'verbose_name_plural': 'Abonnements push',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
