# Generated by Django 4.2.7 on 2025-09-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('register', 'Inscription'), ('profile_update', 'Mise à jour profil'), ('password_change', 'Changement mot de passe'), ('cart_add', 'Ajout au panier'), ('cart_remove', 'Retrait du panier'), ('wishlist_add', 'Ajout aux favoris'), ('wishlist_remove', 'Retrait des favoris')], max_length=20, verbose_name="type d'activité")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateur',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='clé de session')),
                ('query', models.CharField(max_length=200, verbose_name='requête')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='nombre de résultats')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête de recherche',
                'verbose_name_plural': 'Requêtes de recherche',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], max_length=20, verbose_name='type de rapport')),
                ('period_start', models.DateField(verbose_name='début de période')),
                ('period_end', models.DateField(verbose_name='fin de période')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total commandes')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="chiffre d'affaires total")),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='panier moyen')),
                ('new_customers', models.PositiveIntegerField(default=0, verbose_name='nouveaux clients')),
                ('returning_customers', models.PositiveIntegerField(default=0, verbose_name='clients de retour')),
                ('total_products_sold', models.PositiveIntegerField(default=0, verbose_name='produits vendus')),
                ('top_selling_product', models.CharField(blank=True, max_length=200, verbose_name='produit le plus vendu')),
                ('conversion_rate', models.FloatField(default=0.0, verbose_name='taux de conversion')),
                ('cart_abandonment_rate', models.FloatField(default=0.0, verbose_name="taux d'abandon de panier")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
            ],
            options={
                'verbose_name': 'Rapport de ventes',
                'verbose_name_plural': 'Rapports de ventes',
                'ordering': ['-created_at'],
                'unique_together': {('report_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='clé de session')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID produit')),
                ('product_name', models.CharField(max_length=200, verbose_name='nom du produit')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='catégorie')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='prix')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue de produit',
                'verbose_name_plural': 'Vues de produits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='clé de session')),
                ('url', models.URLField(verbose_name='URL')),
                ('referrer', models.URLField(blank=True, verbose_name='référent')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue de page',
                'verbose_name_plural': 'Vues de pages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='clé de session')),
                ('conversion_type', models.CharField(choices=[('purchase', 'Achat'), ('signup', 'Inscription'), ('newsletter', 'Newsletter'), ('contact', 'Contact')], max_length=20, verbose_name='type de conversion')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valeur')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
