# Generated by Django 4.2.7 on 2025-09-20 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('template_type', models.CharField(choices=[('welcome', 'Email de bienvenue'), ('order_confirmation', 'Confirmation de commande'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('password_reset', 'Réinitialisation de mot de passe'), ('newsletter', 'Newsletter'), ('stock_alert', 'Alerte de stock'), ('promotion', 'Promotion'), ('abandoned_cart', 'Panier abandonné')], max_length=50, unique=True, verbose_name='type de template')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('html_content', models.TextField(verbose_name='contenu HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='contenu texte')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Template email',
                'verbose_name_plural': 'Templates email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('content', models.TextField(verbose_name='contenu')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Programmé'), ('sending', "En cours d'envoi"), ('sent', 'Envoyé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='statut')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='programmé pour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('recipients_count', models.PositiveIntegerField(default=0, verbose_name='nombre de destinataires')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'ouvertures")),
                ('clicked_count', models.PositiveIntegerField(default=0, verbose_name='nombre de clics')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='type')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('action_url', models.URLField(blank=True, verbose_name="URL d'action")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='abonné le')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='désabonné le')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abonnement newsletter',
                'verbose_name_plural': 'Abonnements newsletter',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='email destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='sujet')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('bounced', 'Rejeté')], default='pending', max_length=20, verbose_name='statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.emailtemplate')),
            ],
            options={
                'verbose_name': 'Log email',
                'verbose_name_plural': 'Logs email',
                'ordering': ['-created_at'],
            },
        ),
    ]
